---
displayMode: compact
---
gantt
    title Overzicht van arrangement
    dateFormat mm:ss
    axisFormat %S
    tickInterval 8second

    Dwarsfluit          :active, 00:00, 00:16
    [Rust]              :done,   00:16, 00:32
    Dwarsfluit          :active, 00:32, 00:56

    [Rust]              :done,   00:00, 00:08
    Blokfluit           :active, 00:08, 00:32
    [Rust]              :done,   00:32, 00:40
    Blok                :active, 00:40, 00:44
    [Rust]              :done,   00:44, 00:48
    Blokfluit           :active, 00:48, 00:56

    Trommel             :active, 00:00, 00:32
    [Rust]              :done,   00:32, 00:48
    Trommel             :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:16
    Shaker              :active, 00:16, 00:44
    [Rust]              :done,   00:44, 00:48
    Shaker              :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:12
    Harp                :active, 00:12, 00:32
    [Rust]              :done,   00:32, 00:48
    Harp                :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:24
    Piano               :active, 00:24, 00:40
    [Rust]              :done,   00:40, 00:48
    Piano               :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:08
    Gitaar              :active, 00:08, 00:32
    [Rust]              :done,   00:32, 00:48
    Gitaar              :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:32
    Zang                :active, 00:32, 00:56

    [Rust]              :done,   00:00, 00:16
    Viool               :active, 00:16, 00:32
    [Rust]              :done,   00:32, 00:40
    Viool               :active, 00:40, 00:44
    [Rust]              :done,   00:44, 00:48
    Viool               :active, 00:48, 00:56

    Cello               :active, 00:00, 00:32
    [Rust]              :done,   00:32, 00:40
    Cello               :active, 00:40, 00:44
    [Rust]              :done,   00:44, 00:48
    Cello               :active, 00:48, 00:56
