---
displayMode: compact
---
gantt
    title Overzicht van harp
    dateFormat mm:ss
    axisFormat %S
    tickInterval 8second

    [Rust]              :done,   00:00, 00:12
    Harp                :active, 00:12, 00:32
    [Rust]              :done,   00:32, 00:48
    Harp                :active, 00:48, 00:56
