---
displayMode: compact
---
gantt
    title Overzicht van arrangement
    dateFormat mm:ss
    axisFormat %S
    tickInterval 8second

    Dwarsfluit          :active, 00:00, 00:16
    [Rust]              :done,   00:16, 00:32
    Dwarsfluit          :active, 00:32, 00:56

    [Rust]              :done,   00:00, 00:32
    Zang                :active, 00:32, 00:56
