---
displayMode: compact
---
gantt
    title Overzicht van dwarsfluit, harp en piano
    dateFormat mm:ss
    axisFormat %S
    tickInterval 8second

    Dwarsfluit          :active, 00:00, 00:16
    [Rust]              :done,   00:16, 00:32
    Dwarsfluit          :active, 00:32, 00:56

    [Rust]              :done,   00:00, 00:12
    Harp                :active, 00:12, 00:32
    [Rust]              :done,   00:32, 00:48
    Harp                :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:24
    Piano               :active, 00:24, 00:40
    [Rust]              :done,   00:40, 00:48
    Piano               :active, 00:48, 00:56
