---
displayMode: compact
---
gantt
    title Overzicht van dwarsfluit, harp, viool en cello
    dateFormat mm:ss
    axisFormat %S
    tickInterval 8second

    Dwarsfluit          :active, 00:00, 00:16
    [Rust]              :done,   00:16, 00:32
    Dwarsfluit          :active, 00:32, 00:56

    [Rust]              :done,   00:00, 00:12
    Harp                :active, 00:12, 00:32
    [Rust]              :done,   00:32, 00:48
    Harp                :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:16
    Viool               :active, 00:16, 00:32
    [Rust]              :done,   00:32, 00:40
    Viool               :active, 00:40, 00:44
    [Rust]              :done,   00:44, 00:48
    Viool               :active, 00:48, 00:56

    Cello               :active, 00:00, 00:32
    [Rust]              :done,   00:32, 00:40
    Cello               :active, 00:40, 00:44
    [Rust]              :done,   00:44, 00:48
    Cello               :active, 00:48, 00:56
