---
displayMode: compact
---
gantt
    title Overzicht van arrangement
    dateFormat mm:ss
    axisFormat %S
    tickInterval 8second

    Dwarsfluit          :active, 00:00, 00:16
    [Rust]              :done,   00:16, 00:32
    Dwarsfluit          :active, 00:32, 00:56

    Trommel             :active, 00:00, 00:32
    [Rust]              :done,   00:32, 00:48
    Trommel             :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:16
    Shaker              :active, 00:16, 00:44
    [Rust]              :done,   00:44, 00:48
    Shaker              :active, 00:48, 00:56

    [Rust]              :done,   00:00, 00:12
    Harp                :active, 00:12, 00:32
    [Rust]              :done,   00:32, 00:48
    Harp                :active, 00:48, 00:56
